# Generated by Django 3.0 on 2021-08-18 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awad', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='contact',
            new_name='Email',
        ),
    ]
