# Generated by Django 3.0 on 2021-08-18 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awad', '0003_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(default='default.png', upload_to='images/'),
        ),
    ]
