# Generated by Django 3.0 on 2021-08-26 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awad', '0007_revieww'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, default='Blank-Avatar.JPG', null=True, upload_to=''),
        ),
    ]
