# Generated by Django 3.0 on 2021-08-28 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awad', '0009_auto_20210828_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, default='Blank-Avatar.JPG', null=True, upload_to=''),
        ),
    ]
